---
title: "Untitled"
author: "Robin Liu"
date: '2022-07-28'
output: html_document
---

```{r setup, include=FALSE}
library(tidyr)
library(xtable)
library(tables)
source("test_utils.R")
```

```{r}
result <- readRDS("output/p50q50n200reparamTRUEsparse500trials20.rds")
```

```{r}
s <- result$run$s
c_result <- result$run$c_result
g_result <- result$run$g_result
```

```{r}
avg_perf <- rbind(apply(result$gmmreg, 2, mean),
                  apply(result$gmmreg, 2, sd),
                  apply(result$cggr, 2, mean),
                  apply(result$cggr, 2, sd))
colnames(avg_perf) <- c(
  "betaTPR", "betaFPR", "beta_err",
  "meanTPR", "meanFPR", "mean_err", "omega_err")
rownames(avg_perf) <- c("gmmreg", "(sd)", "cggr", "(sd)")
```


### Compare gamma
```{r compare gamma, fig.dim=c(10, 3)}
print(gamma_viz_list(list(
  GMMReg = g_result$ghat,
  CGGR = c_result$ghat,
  Actual = s$mG
)))
```

### Compare beta {.tabset}
```{r, results="asis", echo = F, fig.dim=c(10, 5)}
for (i in seq_len(6)) {
  cat("\n#### comp", i - 1, "\n")
  cov_lbl <- paste0("component ", i - 1)
  cat("\n")
  beta_list <- list(GMMReg = g_result$bhat[,,i],
                    CGGR = c_result$bhat[,,i],
                    Actual = s$tB[,,i])
  print(beta_viz_list(beta_list, cov_lbl, tileborder = T))
  cat("\n")
}
```

