```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("data_generation.R")
source("gmmreg.R")
source("cggr.R")
source("test_utils.R")
library(kableExtra)
library(R.matlab)
library(matlabr)
library(abind)
```

```{r}
set.seed(6)
d <- 10
p <- 20
n <- 200
tB <- generate_tb(d, p, ve = 0.03)
mG <- matrix(runif(d * p, -0.25, 0.25), d, p) #generate_mg(d, p)

generate <- function(n, d, p, tB, mG, seed) {
  set.seed(seed)
  s <- data_generate(n, d, p, tB, mG, reparam = F)
  return(s)
}
```

```{r}
performance <- function(result) {
  stopifnot(all(dim(result$bhat) == dim(tB)))
  stats <- list()
  stats$tpr <- sum(result$bhat != 0 & tB != 0) / sum(tB != 0)
  stats$fpr <- sum(result$bhat != 0 & tB == 0) / sum(tB == 0)
  
  beta_err <- 0
  for (i in 1:d) {
    beta_err <- beta_err + sqrt(sum((tB[i,,] - result$bhat[i,,])^2))
  }
  stats$beta_err <- beta_err

  mean_err <- 0
  for (i in 1:n) {
    mean_err <- mean_err + sum((s$mumx[i, ] -  result$mean(i))^2) / n
  }
  stats$mean_err <- mean_err
  
  
  omega_err <- 0
  iU <- cbind(0, s$U)
  for (i in 1:n) {
    omega <- apply(tB, c(1, 2), \(b) b %*% iU[i, ])
    omhat <- result$precision(i)
    diag(omhat) <- 0
    omega_err <- omega_err + sum((omega - omhat)^2) / n
  }
  stats$omega_err <- omega_err
  
  return(stats)
}
```

## Run methods
```{r}
trials <- 5
s_list = vector("list", length = 5)
for (i in seq_along(s_list)) {
  s_list[[i]] <- generate(n, d, p, tB, mG, seed = i)
}
```


```{r}
gmmreg_results <- vector("list", length = trials)
cggr_results <- vector("list", length = trials)
for (i in seq_along(s_list)) {
  g_result <- gmmreg(s$X, s$U, 0.75)
  c_result <- cggr(s$X, s$U, 0.75)
  gmmreg_results[[i]] <- g_result
  cggr_results[[i]] <- c_result
}  

gmmreg_stats <- matrix(nrow = trials, ncol = 5)
cggr_stats <- matrix(nrow = trials, ncol = 5)
for (i in seq_len(trials)) {
  gmmreg_stats[i,] <- unlist(performance(gmmreg_results[[i]]))
  cggr_stats[i,] <- unlist(performance(cggr_results[[i]]))
}
# 
# stats_gmmreg <- performance(gmmreg_result)
# stats_cggr <- performance(cggr_result)
# rbind(stats_gmmreg, stats_cggr)
# kable(as.data.frame(stats), digits = 3, padding = 10)  |>
#   kable_styling()
```

```{r}
gmmreg_stats
cggr_stats
```


## Compare coefficient matrices
```{r}
for (i in seq_len(6)) {
  cov_lbl <- as.character(i - 1)
  beta_list <- list(GMMReg = gmmreg_results[[1]]$bhat[,,i],
                    CGGR = cggr_results[[1]]$bhat[,,i],
                    Actual = tB[,,i])
  print(beta_viz_list(beta_list, cov_lbl, tileborder = T))
}
```

### Compare gamma
```{r}
print(gamma_viz_list(list(
  GMMReg = gmmreg_results[[1]]$ghat,
  CGGR = cggr_results[[1]]$ghat,
  Actual = mG
)))
```

# Matlab
```{r}
writeMat("GMMReg/GMMReg/gen.mat", resp = s$X, covar = s$U)
run_matlab_script(paste0(getwd(), "/GMMReg/GMMReg/testSerious.m"))
```

Using GMMReg (matlab)
```{r}
result <- readMat("GMMReg/GMMReg/genresult.mat")[[1]]
tuned <- readMat("GMMReg/GMMReg/tunedlambda.mat")$tune
tunedlambda <- tuned[,1]
tunedalpha <- tuned[,2]
resultlist <- apply(result, 3, function(t) t, simplify = F)

stats_matlab <- list()
stats_matlab$tpr <- sum(result != 0 & tB != 0) / sum(tB != 0)
stats_matlab$fpr <- sum(result != 0 & tB == 0) / sum(tB == 0)
stats_matlab$beta_err <- sqrt(sum((tB - result)^2))
# kable(as.data.frame(stats), digits = 3, padding = 10)  |>
#   kable_styling()
stats_matlab
```

### Compare GMMReg (matlab) component matrices
```{r compare components}
for (i in seq_len(6)) {
  cov_lbl <- paste0("component ", i - 1)
  print(beta_viz_compare(result[,,i], tB[,,i], cov_lbl, tileborder = T))
}
```
