---
title: "Untitled"
author: "Robin Liu"
date: '2022-07-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("generate_data.R")
source("cggr_sgl.R")
source("cvxr_node.R")
source("test_utils.R")
```

```{r generate}
set.seed(100)
d <- 5
p <- 10
num <- 200
alpha <- 0.75 # 1 => lasso, 0 => group lasso
s <- generate_data(num, d, p, ve = 0.3, reparametrize = T)
node <- 3
y <- s$responses[, node]
trials <- 10
```

```{r determine_lambda}
centered <- center_vars(s$responses[, -node], s$covariates)
lambda_max <- min_lambda_zero(y, centered$responses, centered$covariates, alpha)
lambda_vals <- rev(10^seq(log10(0.01 * lambda_max),
                         log10(lambda_max), length = trials))
```

```{r}
result <- cggr_sgl(s$responses, s$covariates, lambda = 0.1, alpha = alpha)
gamma_viz(result$gamma_mx)
```


```{r plot}
xlim = c(min(log(lambda_vals)), max(log(lambda_vals)))
ylim = c(-.2, .2)
## Plot results
for (k in c(0, seq_along(s$cov_nz_idx))) {
  nz_idx <- s$cov_nz_idx[k]
  if (k == 0) {
    nz_idx <- 0
  }
  beta_idx <- nz_idx * (d-1) + seq_len(d-1)
  par(mfrow=c(1, 2))
  plot(0, 0, type = "n", main = "CVXR Reg Path",
       xlab = "Log Lambda", ylab = "Coefficients",
       ylim = ylim, xlim = xlim)
  abline(h=0, col = "gray80")
  matlines(log(lambda_vals), beta_vals[, beta_idx])
  nonzero_idx <- which(s$b_mxs[[k + 1]][node, -node] != 0)
  if (length(nonzero_idx) > 0) {
    legend("topright", lty=nonzero_idx, col=nonzero_idx, legend = nonzero_idx)
  }
  
  plot(0, 0, type = "n", main = "My Reg Path",
       xlab = "Log Lambda", ylab = "Coefficients",
       ylim = ylim, xlim = xlim)
  abline(h=0, col = "gray80")
  matlines(log(lambda_vals), my_beta_vals[, beta_idx])
  if (length(nonzero_idx) > 0) {
    legend("topright", lty=nonzero_idx, col=nonzero_idx, legend = nonzero_idx)
  }
}
```

```{r}
## Plot zero coef effects
for (k in (1:p)[-s$cov_nz_idx]) {
  beta_idx <- k * (d-1) + seq_len(d-1)
  par(mfrow=c(1, 2))
  plot(0, 0, type = "n", main = "CVXR Reg Path",
       xlab = "Log Lambda", ylab = "Coefficients",
       ylim = ylim, xlim = xlim)
  abline(h=0, col = "gray80")
  matlines(log(lambda_vals), beta_vals[, beta_idx])
  
  plot(0, 0, type = "n", main = "My Reg Path",
       xlab = "Log Lambda", ylab = "Coefficients",
       ylim = ylim, xlim = xlim)
  abline(h=0, col = "gray80")
  matlines(log(lambda_vals), my_beta_vals[, beta_idx])
}
```


```{r}
gamma_j <- Variable(p)
beta_j <- Variable((p + 1) * (d - 1))
cvxr_result <- cggr_node_cvxr(s$responses[, node],
                              s$responses[, -node],
                              s$covariates, gamma_j, beta_j,
                              lambda_g = 0.03, lambda_b = 0.02, alpha = 0.5)
test_gamma_vals <- cvxr_result$getValue(gamma_j)
test_beta_vals <- cvxr_result$getValue(beta_j)
(test_opt_vals <- cvxr_result$value)
```

```{r}
set.seed(10)
cggr_result <- cggr_node(s$responses[, node],
                         s$responses[, -node],
                         s$covariates,
                         lambda_g = 0.03, lambda_b = 0.02,
                         alpha = 0.5,
                         1000, 1e-5)[[1]]
test_my_gamma_vals <- cggr_result$gamma_j
test_my_beta_vals <- cggr_result$beta_j
(test_my_opt_vals <- cggr_result$obj_val)
```

```{r}
centered <- center_vars(s$responses[, node],
                        s$responses[, -node],
                        s$covariates)
```


```{r}
gj1 <- cvxr_result$getValue(gamma_j)
bj1 <- cvxr_result$getValue(beta_j)
r_j <- compute_residual(centered$y,
                        centered$responses,
                        centered$covariates, gj1, bj1)
compute_obj_value(r_j, gj1, bj1, p, d, 0.03, 0.02, alpha)
```

```{r}
gj2 <- cggr_result$gamma_j
bj2 <- cggr_result$beta_j
r_j <- compute_residual(centered$y,
                        centered$responses,
                        centered$covariates, gj2, bj2)
compute_obj_value(r_j, gj2, bj2, p, d, 0.03, 0.02, alpha)
```
